name: alter
description: "Customize your macOS app icons with ease."
publish_to: "none"
version: 1.1.4

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  desktop_window: ^0.4.2
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.0.0
  macos_ui: ^2.0.9
  objectbox: ^5.0.4
  objectbox_flutter_libs: any
  path: ^1.9.1
  path_provider: ^2.1.5
  process_run: ^1.2.2
  riverpod_annotation: ^3.0.3
  url_launcher: ^6.3.1
  watcher: ^1.1.1

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3
  riverpod_generator: ^3.0.3
  freezed: ^3.0.6
  objectbox_generator: any

flutter:
  uses-material-design: false
  assets:
    - assets/images/alter_empty_dark.png
    - assets/images/alter_empty_light.png
    - assets/images/alter_icon_frame.png
    - macos/Runner/Assets.xcassets/AppIcon.appiconset/icon_512x512@2x.png
